# Generated by Django 3.2.7 on 2021-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('especialidad', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
            },
        ),
    ]
